name: TestDriver.ai / Manual / Explore

permissions:
  actions: read
  contents: write
  pull-requests: write

on:
  push:
  workflow_dispatch:
    inputs:
      prompt:
        description: "Enter the prompt for TestDriver"
        required: true
        default: |
          2. /generate web 10

jobs:
  manual:
    runs-on: ubuntu-latest
    steps:
      - uses: testdriverai/action@main
        with:
          key: ${{ secrets.TESTDRIVER_API_KEY }}
          prompt: ${{ github.event.inputs.prompt }}
          prerun: |
            cd $env:TEMP
            npm init -y
            npm install dashcam-chrome
            choco feature enable -n=allowGlobalConfirmation
            choco install docker-desktop -y
            docker run \
                -e ANTHROPIC_API_KEY=${{ secrets.ANTHRO }} \
                -v $HOME/.anthropic:/home/computeruse/.anthropic \
                -p 5900:5900 \
                -p 8501:8501 \
                -p 6080:6080 \
                -p 8080:8080 \
                -it ghcr.io/anthropics/anthropic-quickstarts:computer-use-demo-latest
            Start-Process "C:/Program Files/Google/Chrome/Application/chrome.exe" -ArgumentList "--start-maximized", "--load-extension=$(pwd)/node_modules/dashcam-chrome/build", "${{ vars.TESTDRIVER_WEBSITE }}"
            exit
          create-pr: true
          pr-title: "TestDriver.ai / Generate Test Plans"
          pr-branch: testdriver/generate-${{ github.run_id }}-${{ github.run_attempt }}
        env:
          FORCE_COLOR: "3"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}